version: "3.7"

services:
  loadbalancer:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:usr/local/etc/haproxy
  node-app1:
    image: nodeapp
    environment:
      - APPID=1111
  node-app2:
    image: nodeapp
    environment:
      - APPID=2222
  node-app3:
    image: nodeapp
    environment:
      - APPID=3333
    